### ISSUE TITLE
Migration from 4.x to 5.0.0

### ISSUE THREAD

**Issue by msa0311** [lensapp/lens#2917]
**What would you like to be added**:
Migration from 4.x to 5

- [x] figure out how to upgrade from 4.x, e.g. Catalog / Hotbar (Migration of Workspaces) (#3075 #3079)
- [x] Disable all Extensions
- [ ] Auto Update Process needs to fetch from Lens-IDE S3 buckets (https://github.com/lensapp/lens/issues/3070)
- [ ] Consider customising Auto Update message with link to e.g. release notes / change list (https://github.com/lensapp/lens/issues/3081)
- [x] Get rid of "Beta" caption everywhere (https://github.com/lensapp/lens/issues/3080)
- [x] Migration of custom cluster icons (https://github.com/lensapp/lens/issues/3057)

Optional:
- Auto Scan Clusters for availability (https://github.com/lensapp/lens/issues/3051)

**Comment by Nokel81** [comment]
Closing this as each item now has its own issue. @msa0311 Should I transfer the `p0` labels to those issues to? I don't think it is necessary as we have already triaged all the previously labelled 5.0.0 issues.
