### ISSUE TITLE
Allow multiple application windows

### ISSUE THREAD

**Issue by jansav** [lensapp/lens#5968]
**What would you like to be added**:
Allow user to start as many application windows they wants.

**Why is this needed**:
There is no reason to limit amount of application windows. User might want to have separate windows for different clusters. 

**What is needed**:
- [x] Figure out when kubeconfig synchronization should start & stop #5982 
- [ ] Figure out when catalog synchronization should start & stop
- [x] Move starting and stopping check for updates to application start/stop #5981
- [ ] Figure out why `lensProtocolRouterMain.rendererLoaded` is needed and replace it with something more elegant
- [ ] Make sure that navigating from e.g. tray, application menu will work properly with multiple windows
  - [x] Replace hard-coded `applicationWindow` with `createApplicationWindow()` which is called once on application start. (`applicationWindow` -> `getCurrentApplicationWindow`) #5979
  - [ ] Introduce a way to detect which application window is "current"
- [x] Allow behavioural testing for multiple windows (remember that there can only be one `document`) #5979
- [ ] Add tray menu items for controlling application windows
- [ ] Add application menu items for controlling application windows

Original: https://github.com/lensapp/lens/issues/431

**Comment by arash-bizcover** [comment]
> Allow user to start as many application windows she wants.

The user is not a she, he uses a male avatar. How rude are you
